stages:
  - test
  - sync

test:golang:1.21:
  stage: test
  image: golang:1.21
  variables:
    CGO_ENABLED: 0
  script:
    - go version
    - go env -w GOPROXY=https://goproxy.cn,direct
    #- go env -w GOPROXY=https://mirrors.aliyun.com/goproxy,direct
    - go mod download
    - go test ./... -v

# 嵌入
include:
  # 同步代码
  - /sync.yml
